<template>
  <div>
    <h1>Scouting Schedule</h1>
    <v-data-table
      :headers="headers"
      :items="items"
      class="elevation-1"
    >
      <template slot="items" slot-scope="props">
        <td>{{ props.item.name }}</td>
        <td class="text-xs-right">{{ props.item.Blue1[0] }}{{ props.item.Blue1[1] }}</td>
        <td class="text-xs-right">{{ props.item.Blue2[0] }}{{ props.item.Blue2[1] }}</td>
        <td class="text-xs-right">{{ props.item.Blue3[0] }}{{ props.item.Blue3[1] }}</td>
        <td class="text-xs-right">{{ props.item.Red1[0] }}{{ props.item.Red1[1] }}</td>
        <td class="text-xs-right">{{ props.item.Red2[0] }}{{ props.item.Red2[1] }}</td>
        <td class="text-xs-right">{{ props.item.Red3[0] }}{{ props.item.Red3[1] }}</td>
      </template>
    </v-data-table>
  </div>
</template>

<script>
export default {
  name: 'TeamAdmin',
  data() {
    const matches = 80;
    const teams = ['Blue1', 'Blue2', 'Blue3', 'Red1', 'Red2', 'Red3'];
    const scouts = new Array(12).fill(0).map((curr, idx) => `Scout ${idx + 1}`);
    const scoutsPerTeam = 2;

    let scoutsEntered = 0;

    const assignments = [];

    for (let match = 0; match < matches; match += 1) {
      assignments[match] = {};
      // eslint-disable-next-line
      for (const team of teams) {
        assignments[match][team] = [];
        for (let scoutSlot = 0; scoutSlot < scoutsPerTeam; scoutSlot += 1) {
          assignments[match][team][scoutSlot] = scouts[scoutsEntered % scouts.length];
          scoutsEntered += 1;
        }
      }
    }
    return {
      headers: [
        {
          text: 'Match Number',
          align: 'center',
          sortable: false,
          value: 'name',
        },
        { text: 'Blue-1', sortable: false, value: '' },
        { text: 'Blue-2', sortable: false, value: '' },
        { text: 'Blue-3', sortable: false, value: '' },
        { text: 'Red-1', sortable: false, value: '' },
        { text: 'Red-2', sortable: false, value: '' },
        { text: 'Red-3', sortable: false, value: '' },
      ],
      items: [
        {
          name: 'Match 1',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 2',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 3',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 4',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 5',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 6',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 7',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 8',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 9',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 10',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 11',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 12',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 13',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 14',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 15',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 16',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 17',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 18',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 19',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 20',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 21',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 22',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 23',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 24',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 25',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 26',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 27',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 28',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 29',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 30',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 31',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 32',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 33',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 34',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 35',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 36',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 37',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 38',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 39',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 40',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 41',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 42',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 43',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 44',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 45',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 46',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 47',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 48',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 49',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 50',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 51',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 52',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 53',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 54',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 55',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 56',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 57',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 58',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 59',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 60',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 61',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 62',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 63',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 64',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 65',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 66',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 67',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 68',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 69 ;)',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 70',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 71',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 72',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 73',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 74',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 75',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 76',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 77',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 78',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 79',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
        {
          name: 'Match 80',
          Blue1: '',
          Blue2: '',
          Blue3: '',
          Red1: '',
          Red2: '',
          Red3: '',
        },
      ],
    };
  },
};
</script>

<style scoped>

</style>
